"""
WattCoin API Error Codes
Standardized error codes for JSON API responses.
Agents can match on 'error_code' to programmatically handle failures.

Usage:
    from api_error_codes import E
    return jsonify({"success": False, "error_code": E.PAYMENT_FAILED, "message": "..."}), 402
"""


class ErrorCodes:
    """Centralized error code constants for all WattCoin API endpoints."""

    # === Payment & Wallet ===
    PAYMENT_FAILED = "WATT_PAYMENT_FAILED"
    PAYMENT_TIMEOUT = "WATT_PAYMENT_TIMEOUT"
    INSUFFICIENT_BALANCE = "WATT_INSUFFICIENT_BALANCE"
    INVALID_WALLET = "WATT_INVALID_WALLET"
    MISSING_WALLET = "WATT_MISSING_WALLET"
    MISSING_TX_SIGNATURE = "WATT_MISSING_TX_SIGNATURE"
    TX_ALREADY_USED = "WATT_TX_ALREADY_USED"
    ALREADY_PAID = "WATT_ALREADY_PAID"

    # === Request Validation ===
    INVALID_REQUEST = "WATT_INVALID_REQUEST"
    INVALID_JSON = "WATT_INVALID_JSON"
    MISSING_FIELD = "WATT_MISSING_FIELD"
    FIELD_TOO_LONG = "WATT_FIELD_TOO_LONG"
    FIELD_TOO_SHORT = "WATT_FIELD_TOO_SHORT"
    UNAUTHORIZED = "WATT_UNAUTHORIZED"
    RATE_LIMITED = "WATT_RATE_LIMITED"

    # === Node Operations ===
    NODE_NOT_FOUND = "WATT_NODE_NOT_FOUND"
    NODE_INACTIVE = "WATT_NODE_INACTIVE"
    NODE_ALREADY_REGISTERED = "WATT_NODE_ALREADY_REGISTERED"
    STAKE_ALREADY_USED = "WATT_STAKE_ALREADY_USED"
    CAPABILITY_INVALID = "WATT_CAPABILITY_INVALID"

    # === LLM Proxy ===
    LLM_ERROR = "WATT_LLM_ERROR"
    MODEL_UNAVAILABLE = "WATT_MODEL_UNAVAILABLE"
    PROMPT_TOO_LONG = "WATT_PROMPT_TOO_LONG"
    MISSING_PROMPT = "WATT_MISSING_PROMPT"

    # === Jobs ===
    JOB_NOT_FOUND = "WATT_JOB_NOT_FOUND"
    JOB_ALREADY_CLAIMED = "WATT_JOB_ALREADY_CLAIMED"
    JOB_ALREADY_COMPLETED = "WATT_JOB_ALREADY_COMPLETED"
    JOB_WRONG_NODE = "WATT_JOB_WRONG_NODE"

    # === Tasks ===
    TASK_NOT_FOUND = "WATT_TASK_NOT_FOUND"
    TASK_CLOSED = "WATT_TASK_CLOSED"
    SUBMISSION_NOT_FOUND = "WATT_SUBMISSION_NOT_FOUND"

    # === Bounties ===
    BOUNTY_NOT_FOUND = "WATT_BOUNTY_NOT_FOUND"
    BOUNTY_ALREADY_CLAIMED = "WATT_BOUNTY_ALREADY_CLAIMED"
    REWARD_TOO_LOW = "WATT_REWARD_TOO_LOW"
    REWARD_TOO_HIGH = "WATT_REWARD_TOO_HIGH"

    # === Scrape ===
    SCRAPE_ERROR = "WATT_SCRAPE_ERROR"


# Shorthand alias
E = ErrorCodes
